import fs from "fs";
import matter from "gray-matter";
import Head from "next/head";
import Link from "next/link";
import path from "path";
import Layout from "../components/Layout";
import Nav from "../components/Nav";
import { postFilePaths, CONTENT_PATCH } from "../utils/mdxUtils";

export default function Index({ posts }) {
  return (
    <>
      <Head>
        <title>Manual de caloure CAEC</title>
      </Head>
      <main>
        <Nav />
        <Layout>
          <h1>Home Page</h1>
          <p>
            Click the link below to navigate to a page generated by{" "}
            <code>next-mdx-remote</code>.
          </p>
          <ul>
            {posts.map((post) => (
              <li key={post.filePath}>
                <Link
                  as={`/${post.filePath.replace(/\.mdx?$/, "")}`}
                  href={`/[slug]`}
                >
                  <a>{post.data.title}</a>
                </Link>
              </li>
            ))}
          </ul>
        </Layout>
      </main>
    </>
  );
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(CONTENT_PATCH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
